### ISSUE TITLE
Null values in response DTOs

### ISSUE THREAD

**Issue by farasadiq** [voucherifyio/voucherify-java-sdk#54]
The following values in io.voucherify.client.model.validation are null when we hit the Voucher Validation API:
1. discount.unitType
2. discount.unitOff
3. voucherType

**Comment by lkulig** [comment]
@farasadiq 
I checked and:
* discount.unitOff is properly returned.
* discount.unitType is currently not possible to specify via SDK when creating voucher, thus not available when validating voucher - will be fixed in next release.
* VoucherType is not and won't be returned - this field will also be removed with the next release.

**Comment by asadyarkhan007** [comment]
Hi why did you close the ticket ?
discount.unitOff does not return over validate and redeem call. Kindly recheck
we are using the 6.0.1 SDK.
unitType to display. Kindly fix it soon

VoucherType is not and won't be returned? Why 
We need to process voucher type whether discount voucher or gift voucher.
